### ISSUE TITLE
An error occurs when downloading dataset

### ISSUE THREAD

**Issue by sc841101** [ceciliavision/zoom-learn-zoom#1]
Hi,

Thanks for open sourcing your code and dataset.

I got an an error when downloading train.zip file with your script.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   388    0   388    0     0   1001      0 --:--:-- --:--:-- --:--:--  1000
100  9.9G    0  9.9G    0     0  43.2M      0 --:--:--  0:03:56 --:--:-- 33.9M
curl: (56) GnuTLS recv error (-9): A TLS packet with unexpected length was received.

I also tried downloading with Google Drvie in Windows7 enviroment.
However, I also got a network error.

By the way, I can download test.zip successfully.

Thanks.

**Comment by ceciliavision** [comment]
How about downloading directly from the folder [https://drive.google.com/drive/folders/1UHKEUp77tiCZ9y05JtP6S9Tfo2RftK8m](url)?

**Comment by ceciliavision** [comment]
Can you try downloading from the Gdrive folder manually (not using the script?)

**Comment by Adhders** [comment]
> Hi,
> 
> Thanks for open sourcing your code and dataset.
> 
> I got an an error when downloading train.zip file with your script.
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 100 388 0 388 0 0 1001 0 --:--:-- --:--:-- --:--:-- 1000
> 100 9.9G 0 9.9G 0 0 43.2M 0 --:--:-- 0:03:56 --:--:-- 33.9M
> curl: (56) GnuTLS recv error (-9): A TLS packet with unexpected length was received.
> 
> I also tried downloading with Google Drvie in Windows7 enviroment.
> However, I also got a network error.
> 
> By the way, I can download test.zip successfully.
> 


dear friend, can you share the file by Baidu Netdisk,I am not able to access the Google Drive, very thanks to you

**Comment by sc841101** [comment]
> Can you try downloading from the Gdrive folder manually (not using the script?)

The error also occurred when downloading from Gdrive folder.
The same as using the script, it stopped downloading at 9.9G.

**Comment by ceciliavision** [comment]
I'm able to download it without trouble. Can you first verify you have enough space in your local disk?
Also, I will later upload the model to some other cloud storage platform that's more accessible.

**Comment by llp1996** [comment]
i am not able to download the datasets from google drive,too.i think it could exist some error between my shadowsocks and google drive,,,sigh~

**Comment by ceciliavision** [comment]
Please refer to [this issue](https://github.com/ceciliavision/zoom-learn-zoom/issues/8#issue-456526689) for a dataset link on Baidu drive.
