### ISSUE TITLE
the sky is dirty issue

### ISSUE THREAD

**Issue by SandyJ01** [ceciliavision/zoom-learn-zoom#19]
when I use  CoBiVGG to train my own data, the sky is very dirty, including dark line and dark border, do you know why it occurs? and can you please tell me the possible reason?

**Comment by ceciliavision** [comment]
There might be hyperparameter tuning needed to train on a completely different dataset. It would depend on the size, the types of raw sensor data, the noise level during capture (very high noise would cause unstable training using CoBi), etc.
