### ISSUE TITLE
About dataset downloading.

### ISSUE THREAD

**Issue by musicrainie** [ceciliavision/zoom-learn-zoom#2]
Thanks for your greak work.
Can you provide a BaiduCloudDisk link for the dataset?

**Comment by Adhders** [comment]
> Thanks for your greak work.
> Can you provide a BaiduCloudDisk link for the dataset?

same trouble !

**Comment by ceciliavision** [comment]
Please refer to[ this issue](https://github.com/ceciliavision/zoom-learn-zoom/issues/8#issue-456526689) for the link to Baidu Drive.
