### ISSUE TITLE
How to use tform.txt and wb.txt during training?

### ISSUE THREAD

**Issue by IanYeung** [ceciliavision/zoom-learn-zoom#21]
Hi, I would like to know how you use tform.txt and wb.txt during training. How do you obtain corresponding raw-L and rgb-H during training?

**Comment by ceciliavision** [comment]
Please see a newly added [notebook demo](https://github.com/ceciliavision/zoom-learn-zoom/blob/master/demo_rawrgb_pair.ipynb).
