### ISSUE TITLE
what the function get_transformed_corner() mean?

### ISSUE THREAD

**Issue by luyao1** [ceciliavision/zoom-learn-zoom#27]
can you offer the function of get_transformed_corner() code?

**Comment by ceciliavision** [comment]
it's now in the utils.py function.
It computes how the corners of the images are transformed, so that it applies corresponding cropping to the raw image. Please see a newly added [notebook demo](https://github.com/ceciliavision/zoom-learn-zoom/blob/master/demo_rawrgb_pair.ipynb) for details.
