### ISSUE TITLE
Question about released models

### ISSUE THREAD

**Issue by Ding-Liu** [ceciliavision/zoom-learn-zoom#4]
Hi,

First, thanks a lot for sharing your code and dataset! Here I just have two questions about your released model:

I checked its architecture via Tensorboard, and it seems to be an 8x but not 4x model. Is that correct?

Do you plan to release your 4x model as well? I would really appreciate it if you do so!

Many thanks again!

**Comment by llp1996** [comment]
the model is raw bayer to rgb ,so you see raw bayer input has a 8x ratio with rgb output ,but raw bayer as a network input is 4 channels ,,so actually the released model is a 4x model !

**Comment by llp1996** [comment]
> Hi,
> 
> First, thanks a lot for sharing your code and dataset! Here I just have two questions about your released model:
> 
> I checked its architecture via Tensorboard, and it seems to be an 8x but not 4x model. Is that correct?
> 
> Do you plan to release your 4x model as well? I would really appreciate it if you do so!
> 
> Many thanks again!

the model is raw bayer to rgb ,so you see raw bayer input has a 8x ratio with rgb output ,but raw bayer as a network input is 4 channels ,,so actually the released model is a 4x model !

**Comment by ceciliavision** [comment]
Yes @llp1996 is correct. Thanks for explaining
