### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by llp1996** [ceciliavision/zoom-learn-zoom#5]
i don't find training code in the file ,could you provide your training code? thanks 

and , could i upload training data to Baidu Drive in China?

**Comment by yanmenglu** [comment]
@llp1996 I cannot download the SR_RAW dataset, could you help me?
could you upload the data to Baidu Drive?

**Comment by ceciliavision** [comment]
> could i upload training data to Baidu Drive in China?

Yes you can, please forward me a link and I will patch it to this repo. Thanks
