### ISSUE TITLE
data set Baidu drive link

### ISSUE THREAD

**Issue by llp1996** [ceciliavision/zoom-learn-zoom#8]
i upload the dataset to baidu drive !
the link is：https://pan.baidu.com/s/1pRu7DDnpUYaPdXY8Rlb6UQ 
the key is ：wi02 
help youself!

**Comment by ceciliavision** [comment]
This is very helpful, thanks! I will update the README with the link.

**Comment by jiandandan001** [comment]
> i upload the dataset to baidu drive !
> the link is：https://pan.baidu.com/s/1pRu7DDnpUYaPdXY8Rlb6UQ
> the key is ：wi02
> hope it can help

Hi. Thank you for uploading the train data to Baidu drive.
Could you please upload the test data part to the Baidu drive? Thanks
